services:
  claude-remote:
    build: .
    container_name: claude-remote-api
    ports:
      - "3950:3950"
    environment:
      - NODE_ENV=production
      - PORT=3950
    volumes:
      # Mount repos directory to persist cloned repositories
      - ./repos:/app/repos
      # Mount .env file if it exists
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3950/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - claude-remote-network

networks:
  claude-remote-network:
    driver: bridge
